### ISSUE TITLE
プラグインのメソッドが呼び出されるたびにプラグインの情報ボックスがポップアップするのは、スクリプトの使い勝手を悪くします

### ISSUE THREAD

**Issue by moelody** [atarabi/at_script#3]
インフォボックスが呼び出されるたびにポップアップするのではなく、最初の使用時に一度だけポップアップするようにして、インフォボックスのポップアップを減らすことができればと思います。

**Comment by atarabi** [comment]
Thanks for the report. I can't reproduce it in my environment, so could you send me a video?

**Comment by moelody** [comment]
https://github.com/atarabi/at_script/assets/30750380/2dbe75f3-2e95-4c3f-82cc-0bde472f6907

After I kept debugging, I found that the problem seems to be caused by the method `app.activeViewer.setActive`. When trying to activate the composite using this method it triggers the popup window

> Thanks for the report. I can't reproduce it in my environment, so could you send me a video?

**Comment by atarabi** [comment]
Hmmm, I ran the same script and couldn't reproduce it.
So I couldn't find the root cause, but I came up with a workaround and implemented it.
Could you try it?
[@script.zip](https://github.com/atarabi/at_script/files/14845484/%40script.zip)

**Comment by moelody** [comment]
It works! The plugin is not popping up as often because of setting active, thanks for your work!👍
