### ISSUE TITLE
saveCustomValueメソッドで保存されたファイルデータはどのように使用しますか？レイヤーに再適用するにはどうすればいいですか？

### ISSUE THREAD

**Issue by moelody** [atarabi/at_script#5]

**Comment by atarabi** [comment]
Currently, there is no method available to apply the binary data obtained by saveCustomValue.
If you want to get the value of the custom property and apply that value again, please use Atarabi.property.getValue and Atarbai.property.setValue.
Note that applying to some custom properties (e.g., Mesh Warp, Reshape) may cause crashes.

**Comment by atarabi** [comment]
loadCustomValue has been added in v0.4.1.
