### ISSUE TITLE
An error occurs when I try to use `Atarabi.property.isHidden` to determine if a property under the Effect Composition options is hidden or not

### ISSUE THREAD

**Issue by moelody** [atarabi/at_script#7]
Properties with matchName of `ADBE Force CPU GPU` and `ADBE Effect Mask Opacity` report errors
![image](https://github.com/user-attachments/assets/0c18c593-5738-4650-a226-9e24fcb30ace)
Mask Reference `ADBE Effect Path Stream Ref` also.

**Comment by atarabi** [comment]
Thank you for reporting this issue.
I've found the cause and fixed it.
I will be able to provide a fixed version soon.

**Comment by atarabi** [comment]
fixed in v0.4.1.
